"""
Site database for TraceHunter-CLI.
Built-in curated collection of 200+ high-value sites for username search.
Each site entry contains detection signatures for reliable account discovery.
"""

# Site categories
CATEGORIES = {
    "social": "Social Media & Networking",
    "tech": "Technology & Development",
    "media": "Content & Media",
    "gaming": "Gaming & Entertainment",
    "finance": "Finance & Business",
    "education": "Education & Research",
    "forum": "Forums & Communities",
    "shopping": "Shopping & Marketplace",
    "other": "Other Platforms",
}

SITES = [
    # ===== SOCIAL MEDIA =====
    {
        "name": "twitter",
        "category": "social",
        "url": "https://twitter.com/{username}",
        "check_url": "https://twitter.com/i/users/username_available?username={username}",
        "presence_strs": ["\"taken\":true", "\"valid\":true", "\"available\":false"],
        "absence_strs": ["\"taken\":false", "\"available\":true", "not found"],
        "method": "json",
        "tags": ["popular", "microblog"],
    },
    {
        "name": "github",
        "category": "tech",
        "url": "https://github.com/{username}",
        "presence_strs": ["<meta name=\"description\" content=\"", "contributions", "repositories"],
        "absence_strs": ["Page not found", "is not a registered user", "404"],
        "method": "html",
        "tags": ["popular", "code", "vcs"],
    },
    {
        "name": "instagram",
        "category": "social",
        "url": "https://www.instagram.com/{username}/",
        "presence_strs": ["\"@{}", "\"edge_owner_to_timeline_media\"", "\"profile_pic_url\""],
        "absence_strs": ["Sorry, this page", "Page Not Found", "\"is_private\":false"],
        "method": "json",
        "tags": ["popular", "photo", "video"],
    },
    {
        "name": "reddit",
        "category": "social",
        "url": "https://www.reddit.com/user/{username}",
        "presence_strs": ["cake day", "karma", "post_karma", "comment_karma"],
        "absence_strs": ["page not found", "does not exist", "404"],
        "method": "html",
        "tags": ["popular", "forum", "news"],
    },
    {
        "name": "linkedin",
        "category": "social",
        "url": "https://www.linkedin.com/in/{username}",
        "presence_strs": ["LinkedIn", "profile", "experience"],
        "absence_strs": ["not found", "404", "page could not be found"],
        "method": "html",
        "tags": ["popular", "professional", "business"],
    },
    {
        "name": "youtube",
        "category": "media",
        "url": "https://www.youtube.com/@{username}",
        "presence_strs": ["\"@{}", "\"subscriberCount\"", "\"videoCount\""],
        "absence_strs": ["This channel doesn't exist", "404", "Not Found"],
        "method": "html",
        "tags": ["popular", "video"],
    },
    {
        "name": "tiktok",
        "category": "social",
        "url": "https://www.tiktok.com/@{username}",
        "presence_strs": ["\"uniqueId\":\"{}\"", "\"followerCount\"", "\"nickname\""],
        "absence_strs": ["Couldn't find", "not found", "404"],
        "method": "html",
        "tags": ["popular", "video", "short"],
    },
    {
        "name": "facebook",
        "category": "social",
        "url": "https://www.facebook.com/{username}",
        "presence_strs": ["content=\"Facebook", "profile", "timeline"],
        "absence_strs": ["not found", "page isn't available", "404"],
        "method": "html",
        "tags": ["popular", "social"],
    },
    {
        "name": "pinterest",
        "category": "social",
        "url": "https://www.pinterest.com/{username}/",
        "presence_strs": ["\"username\":\"{}\"", "pinterest", "pins"],
        "absence_strs": ["not found", "404", "doesn't exist"],
        "method": "html",
        "tags": ["popular", "photo", "bookmark"],
    },
    {
        "name": "tumblr",
        "category": "social",
        "url": "https://{username}.tumblr.com",
        "presence_strs": ["tumblr", "posts", "liked"],
        "absence_strs": ["not found", "404", "There's nothing here"],
        "method": "html",
        "tags": ["popular", "blog", "microblog"],
    },
    {
        "name": "snapchat",
        "category": "social",
        "url": "https://www.snapchat.com/add/{username}",
        "presence_strs": ["snapchat", "add", "username"],
        "absence_strs": ["not found", "404", "User Not Found"],
        "method": "html",
        "tags": ["popular", "messaging", "photo"],
    },
    {
        "name": "mastodon",
        "category": "social",
        "url": "https://mastodon.social/@{username}",
        "presence_strs": ["\"@{}@", "toot", "followers"],
        "absence_strs": ["not found", "404", "The page you are looking for"],
        "method": "html",
        "tags": ["federated", "microblog"],
    },
    {
        "name": "threads",
        "category": "social",
        "url": "https://www.threads.net/@{username}",
        "presence_strs": ["\"@{}\"", "threads", "replies"],
        "absence_strs": ["not found", "404", "Sorry"],
        "method": "html",
        "tags": ["popular", "microblog", "meta"],
    },
    {
        "name": "bluesky",
        "category": "social",
        "url": "https://bsky.app/profile/{username}",
        "presence_strs": ["\"did:", "\"handle\":\"{}\"", "follows"],
        "absence_strs": ["not found", "404", "Could not find"],
        "method": "html",
        "tags": ["popular", "microblog", "decentralized"],
    },
    {
        "name": "x",
        "category": "social",
        "url": "https://x.com/{username}",
        "presence_strs": ["<meta name=\"description\" content=\"", "followers", "following"],
        "absence_strs": ["Page not found", "does not exist", "404"],
        "method": "html",
        "tags": ["popular", "microblog"],
    },
    # ===== TECH & DEVELOPMENT =====
    {
        "name": "gitlab",
        "category": "tech",
        "url": "https://gitlab.com/{username}",
        "presence_strs": ["\"username\":\"{}\"", "projects", "contributions"],
        "absence_strs": ["not found", "404", "does not exist"],
        "method": "html",
        "tags": ["code", "vcs", "devops"],
    },
    {
        "name": "stackoverflow",
        "category": "tech",
        "url": "https://stackoverflow.com/users/{username}",
        "presence_strs": ["Stack Overflow", "reputation", "answers"],
        "absence_strs": ["not found", "404", "Users - Stack Overflow"],
        "method": "html",
        "tags": ["popular", "qa", "programming"],
    },
    {
        "name": "dev.to",
        "category": "tech",
        "url": "https://dev.to/{username}",
        "presence_strs": ["DEV Community", "profile", "articles"],
        "absence_strs": ["not found", "404", "Page not found"],
        "method": "html",
        "tags": ["blog", "programming", "community"],
    },
    {
        "name": "medium",
        "category": "tech",
        "url": "https://medium.com/@{username}",
        "presence_strs": ["Medium", "profile", "stories"],
        "absence_strs": ["not found", "404", "PAGE NOT FOUND"],
        "method": "html",
        "tags": ["popular", "blog", "writing"],
    },
    {
        "name": "npmjs",
        "category": "tech",
        "url": "https://www.npmjs.com/~{username}",
        "presence_strs": ["npm", "packages", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["javascript", "package", "registry"],
    },
    {
        "name": "pypi",
        "category": "tech",
        "url": "https://pypi.org/user/{username}/",
        "presence_strs": ["PyPI", "packages", "profile"],
        "absence_strs": ["not found", "404", "User not found"],
        "method": "html",
        "tags": ["python", "package", "registry"],
    },
    {
        "name": "dockerhub",
        "category": "tech",
        "url": "https://hub.docker.com/u/{username}",
        "presence_strs": ["Docker Hub", "repositories", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["docker", "container", "registry"],
    },
    {
        "name": "hackernews",
        "category": "tech",
        "url": "https://news.ycombinator.com/user?id={username}",
        "presence_strs": ["user:", "created:", "karma:"],
        "absence_strs": ["No such user", "404"],
        "method": "html",
        "tags": ["popular", "news", "startup"],
    },
    {
        "name": "keybase",
        "category": "tech",
        "url": "https://keybase.io/{username}",
        "presence_strs": ["keybase", "profile", "public key"],
        "absence_strs": ["not found", "404", "does not exist"],
        "method": "html",
        "tags": ["encryption", "identity", "security"],
    },
    {
        "name": "replit",
        "category": "tech",
        "url": "https://replit.com/@{username}",
        "presence_strs": ["Replit", "profile", "projects"],
        "absence_strs": ["not found", "404", "doesn't exist"],
        "method": "html",
        "tags": ["ide", "coding", "cloud"],
    },
    {
        "name": "codepen",
        "category": "tech",
        "url": "https://codepen.io/{username}",
        "presence_strs": ["CodePen", "pen", "profile"],
        "absence_strs": ["not found", "404", "User not found"],
        "method": "html",
        "tags": ["frontend", "code", "editor"],
    },
    {
        "name": "vercel",
        "category": "tech",
        "url": "https://vercel.com/{username}",
        "presence_strs": ["Vercel", "projects", "deployments"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["deployment", "hosting", "frontend"],
    },
    {
        "name": "netlify",
        "category": "tech",
        "url": "https://app.netlify.com/sites",
        "check_url": "https://app.netlify.com/v1/users/{username}",
        "presence_strs": ["\"id\"", "\"email\"", "\"created_at\""],
        "absence_strs": ["not found", "404", "User not found"],
        "method": "json",
        "tags": ["deployment", "hosting", "frontend"],
    },
    {
        "name": "hashnode",
        "category": "tech",
        "url": "https://hashnode.com/@{username}",
        "presence_strs": ["Hashnode", "blog", "posts"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["blog", "programming", "writing"],
    },
    {
        "name": "polywork",
        "category": "social",
        "url": "https://polywork.com/{username}",
        "presence_strs": ["Polywork", "profile", "highlights"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["professional", "portfolio"],
    },
    # ===== CONTENT & MEDIA =====
    {
        "name": "vimeo",
        "category": "media",
        "url": "https://vimeo.com/{username}",
        "presence_strs": ["Vimeo", "videos", "profile"],
        "absence_strs": ["not found", "404", "doesn't exist"],
        "method": "html",
        "tags": ["video", "creative"],
    },
    {
        "name": "soundcloud",
        "category": "media",
        "url": "https://soundcloud.com/{username}",
        "presence_strs": ["SoundCloud", "tracks", "followers"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["music", "audio", "streaming"],
    },
    {
        "name": "spotify",
        "category": "media",
        "url": "https://open.spotify.com/user/{username}",
        "presence_strs": ["Spotify", "playlists", "followers"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["popular", "music", "streaming"],
    },
    {
        "name": "twitch",
        "category": "media",
        "url": "https://www.twitch.tv/{username}",
        "presence_strs": ["Twitch", "followers", "videos"],
        "absence_strs": ["not found", "404", "doesn't exist"],
        "method": "html",
        "tags": ["popular", "streaming", "gaming"],
    },
    {
        "name": "flickr",
        "category": "media",
        "url": "https://www.flickr.com/people/{username}/",
        "presence_strs": ["Flickr", "photostream", "photos"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["photo", "sharing"],
    },
    {
        "name": "behance",
        "category": "media",
        "url": "https://www.behance.net/{username}",
        "presence_strs": ["Behance", "projects", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["design", "portfolio", "creative"],
    },
    {
        "name": "dribbble",
        "category": "media",
        "url": "https://dribbble.com/{username}",
        "presence_strs": ["Dribbble", "shots", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["design", "portfolio", "creative"],
    },
    {
        "name": "substack",
        "category": "media",
        "url": "https://{username}.substack.com",
        "presence_strs": ["Substack", "newsletter", "posts"],
        "absence_strs": ["not found", "404", "doesn't exist"],
        "method": "html",
        "tags": ["newsletter", "blog", "writing"],
    },
    {
        "name": "patreon",
        "category": "media",
        "url": "https://www.patreon.com/{username}",
        "presence_strs": ["Patreon", "creator", "tiers"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["creator", "funding", "membership"],
    },
    {
        "name": "wordpress",
        "category": "media",
        "url": "https://{username}.wordpress.com",
        "presence_strs": ["WordPress.com", "blog", "posts"],
        "absence_strs": ["not found", "404", "doesn't exist"],
        "method": "html",
        "tags": ["blog", "cms", "popular"],
    },
    # ===== GAMING =====
    {
        "name": "steam",
        "category": "gaming",
        "url": "https://steamcommunity.com/id/{username}",
        "presence_strs": ["Steam Community", "profile", "games"],
        "absence_strs": ["not found", "404", "Sorry"],
        "method": "html",
        "tags": ["popular", "gaming", "pc"],
    },
    {
        "name": "roblox",
        "category": "gaming",
        "url": "https://www.roblox.com/users/profile",
        "check_url": "https://users.roblox.com/v1/users/search?keyword={username}&limit=1",
        "presence_strs": ["\"id\"", "\"name\":\"{}\"", "\"displayName\""],
        "absence_strs": ["[]"],
        "method": "json",
        "tags": ["popular", "gaming", "social"],
    },
    {
        "name": "discord",
        "category": "gaming",
        "url": "https://discord.com/users/{username}",
        "presence_strs": ["Discord", "user", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["popular", "messaging", "gaming"],
    },
    {
        "name": "twitch_gaming",
        "category": "gaming",
        "url": "https://www.twitch.tv/{username}",
        "presence_strs": ["Twitch", "stream", "followers"],
        "absence_strs": ["not found", "404", "doesn't exist"],
        "method": "html",
        "tags": ["streaming", "gaming"],
    },
    # ===== FORUMS & COMMUNITIES =====
    {
        "name": "quora",
        "category": "forum",
        "url": "https://www.quora.com/profile/{username}",
        "presence_strs": ["Quora", "profile", "answers"],
        "absence_strs": ["not found", "404", "Page not found"],
        "method": "html",
        "tags": ["popular", "qa", "knowledge"],
    },
    {
        "name": "producthunt",
        "category": "forum",
        "url": "https://www.producthunt.com/@{username}",
        "presence_strs": ["Product Hunt", "profile", "products"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["popular", "startup", "products"],
    },
    {
        "name": "indiehackers",
        "category": "forum",
        "url": "https://www.indiehackers.com/{username}",
        "presence_strs": ["Indie Hackers", "profile", "posts"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["startup", "entrepreneur", "community"],
    },
    # ===== FINANCE & BUSINESS =====
    {
        "name": "aboutme",
        "category": "social",
        "url": "https://about.me/{username}",
        "presence_strs": ["about.me", "profile", "bio"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["personal", "portfolio", "bio"],
    },
    {
        "name": "gravatar",
        "category": "social",
        "url": "https://gravatar.com/{username}",
        "presence_strs": ["Gravatar", "profile"],
        "absence_strs": ["not found", "404"],
        "method": "html",
        "tags": ["avatar", "identity"],
    },
    {
        "name": "ko-fi",
        "category": "finance",
        "url": "https://ko-fi.com/{username}",
        "presence_strs": ["Ko-fi", "support", "gallery"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["creator", "funding", "support"],
    },
    {
        "name": "buymeacoffee",
        "category": "finance",
        "url": "https://buymeacoffee.com/{username}",
        "presence_strs": ["Buy Me a Coffee", "supporter", "creator"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["creator", "funding", "support"],
    },
    {
        "name": "gumroad",
        "category": "finance",
        "url": "https://{username}.gumroad.com",
        "presence_strs": ["Gumroad", "products", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["creator", "products", "selling"],
    },
    # ===== EDUCATION & RESEARCH =====
    {
        "name": "scholar",
        "category": "education",
        "url": "https://scholar.google.com/citations?user={username}",
        "presence_strs": ["Google Scholar", "citations", "profile"],
        "absence_strs": ["not found", "404", "not a valid user"],
        "method": "html",
        "tags": ["research", "academic", "citations"],
    },
    {
        "name": "orcid",
        "category": "education",
        "url": "https://orcid.org/{username}",
        "presence_strs": ["ORCID", "profile", "works"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["research", "academic", "identity"],
    },
    {
        "name": "kaggle",
        "category": "education",
        "url": "https://www.kaggle.com/{username}",
        "presence_strs": ["Kaggle", "profile", "competitions"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["data", "ml", "competition"],
    },
    # ===== ADDITIONAL POPULAR SITES =====
    {
        "name": "angellist",
        "category": "finance",
        "url": "https://wellfound.com/u/{username}",
        "presence_strs": ["Wellfound", "profile", "startup"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["startup", "investing", "professional"],
    },
    {
        "name": "tripadvisor",
        "category": "other",
        "url": "https://www.tripadvisor.com/Profile/{username}",
        "presence_strs": ["Tripadvisor", "profile", "contributions"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["travel", "review"],
    },
    {
        "name": "yelp",
        "category": "other",
        "url": "https://www.yelp.com/user_details?userid={username}",
        "presence_strs": ["Yelp", "profile", "reviews"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["review", "local", "business"],
    },
    {
        "name": "amazon",
        "category": "shopping",
        "url": "https://www.amazon.com/sp?seller={username}",
        "presence_strs": ["Amazon", "seller", "storefront"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["popular", "shopping", "marketplace"],
    },
    {
        "name": "ebay",
        "category": "shopping",
        "url": "https://www.ebay.com/usr/{username}",
        "presence_strs": ["eBay", "feedback", "seller"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["popular", "shopping", "auction"],
    },
    {
        "name": "etsy",
        "category": "shopping",
        "url": "https://www.etsy.com/shop/{username}",
        "presence_strs": ["Etsy", "shop", "items"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["handmade", "shopping", "creative"],
    },
    {
        "name": "itchio",
        "category": "gaming",
        "url": "https://{username}.itch.io",
        "presence_strs": ["itch.io", "profile", "games"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["indie", "gaming", "creator"],
    },
    {
        "name": "bandcamp",
        "category": "media",
        "url": "https://{username}.bandcamp.com",
        "presence_strs": ["Bandcamp", "music", "album"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["music", "independent", "artist"],
    },
    {
        "name": "lastfm",
        "category": "media",
        "url": "https://www.last.fm/user/{username}",
        "presence_strs": ["Last.fm", "scrobbles", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["music", "listening", "stats"],
    },
    {
        "name": "goodreads",
        "category": "other",
        "url": "https://www.goodreads.com/user/show/{username}",
        "presence_strs": ["Goodreads", "profile", "books"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["books", "reading", "review"],
    },
    {
        "name": "letterboxd",
        "category": "media",
        "url": "https://letterboxd.com/{username}/",
        "presence_strs": ["Letterboxd", "films", "watched"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["film", "movies", "review"],
    },
    {
        "name": "rateyourmusic",
        "category": "media",
        "url": "https://rateyourmusic.com/~{username}",
        "presence_strs": ["Rate Your Music", "profile", "ratings"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["music", "ratings", "database"],
    },
    {
        "name": "archiveorg",
        "category": "tech",
        "url": "https://archive.org/details/@{username}",
        "presence_strs": ["Internet Archive", "uploads", "reviews"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["archive", "digital", "library"],
    },
    {
        "name": "cloudflare",
        "category": "tech",
        "url": "https://1.1.1.1/dns-query?name={username}.cloudflare.com",
        "presence_strs": ["NOERROR", "0 0 0 0"],
        "absence_strs": ["NXDOMAIN"],
        "method": "json",
        "tags": ["dns", "hosting", "infrastructure"],
    },
    {
        "name": "sourcehut",
        "category": "tech",
        "url": "https://sr.ht/~{username}",
        "presence_strs": ["sourcehut", "profile", "repos"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["code", "vcs", "minimal"],
    },
    {
        "name": "codeberg",
        "category": "tech",
        "url": "https://codeberg.org/{username}",
        "presence_strs": ["Codeberg", "profile", "repositories"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["code", "vcs", "federated"],
    },
    {
        "name": "jsfiddle",
        "category": "tech",
        "url": "https://jsfiddle.net/user/{username}/",
        "presence_strs": ["JSFiddle", "fiddles", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["frontend", "code", "editor"],
    },
    {
        "name": "hackerearth",
        "category": "education",
        "url": "https://www.hackerearth.com/@{username}",
        "presence_strs": ["HackerEarth", "profile", "challenges"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["competitive", "programming", "hiring"],
    },
    {
        "name": "hackerrank",
        "category": "education",
        "url": "https://www.hackerrank.com/{username}",
        "presence_strs": ["HackerRank", "profile", "certificates"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["competitive", "programming", "skills"],
    },
    {
        "name": "leetcode",
        "category": "education",
        "url": "https://leetcode.com/{username}/",
        "presence_strs": ["LeetCode", "problems", "submissions"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["popular", "competitive", "programming"],
    },
    {
        "name": "codewars",
        "category": "education",
        "url": "https://www.codewars.com/users/{username}",
        "presence_strs": ["Codewars", "honor", "kyu"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["competitive", "programming", "gamified"],
    },
    {
        "name": "topcoder",
        "category": "education",
        "url": "https://www.topcoder.com/members/{username}/",
        "presence_strs": ["Topcoder", "profile", "challenges"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["competitive", "programming", "enterprise"],
    },
    {
        "name": "lichess",
        "category": "gaming",
        "url": "https://lichess.org/@/{username}",
        "presence_strs": ["lichess", "rating", "games"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["chess", "gaming", "open"],
    },
    {
        "name": "chesscom",
        "category": "gaming",
        "url": "https://www.chess.com/member/{username}",
        "presence_strs": ["Chess.com", "rating", "games"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["chess", "gaming", "popular"],
    },
    {
        "name": "opensea",
        "category": "finance",
        "url": "https://opensea.io/{username}",
        "presence_strs": ["OpenSea", "profile", "NFTs"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["nft", "crypto", "marketplace"],
    },
    {
        "name": "pastebin",
        "category": "tech",
        "url": "https://pastebin.com/u/{username}",
        "presence_strs": ["Pastebin", "pastes", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["paste", "text", "sharing"],
    },
    {
        "name": "slideshare",
        "category": "education",
        "url": "https://www.slideshare.net/{username}",
        "presence_strs": ["SlideShare", "presentations", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["presentation", "sharing", "professional"],
    },
    {
        "name": "speakerdeck",
        "category": "education",
        "url": "https://speakerdeck.com/{username}",
        "presence_strs": ["Speaker Deck", "presentations", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["presentation", "sharing", "professional"],
    },
    {
        "name": "figma",
        "category": "tech",
        "url": "https://www.figma.com/@{username}",
        "presence_strs": ["Figma", "profile", "files"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["design", "collaboration", "popular"],
    },
    {
        "name": "canva",
        "category": "tech",
        "url": "https://www.canva.com/@{username}",
        "presence_strs": ["Canva", "profile", "designs"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["design", "popular", "templates"],
    },
    {
        "name": "notion",
        "category": "tech",
        "url": "https://www.notion.so/{username}",
        "presence_strs": ["Notion", "page", "workspace"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["productivity", "workspace", "popular"],
    },
    {
        "name": "obsidian",
        "category": "tech",
        "url": "https://publish.obsidian.md/{username}",
        "presence_strs": ["Obsidian", "publish", "notes"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["notes", "knowledge", "publishing"],
    },
    {
        "name": "strava",
        "category": "other",
        "url": "https://www.strava.com/athletes/{username}",
        "presence_strs": ["Strava", "activities", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["fitness", "running", "cycling"],
    },
    {
        "name": "medium2",
        "category": "tech",
        "url": "https://medium.com/@{username}",
        "presence_strs": ["Medium", "Member since", "profile"],
        "absence_strs": ["not found", "404", "PAGE NOT FOUND"],
        "method": "html",
        "tags": ["blog", "writing", "tech"],
    },
    {
        "name": "telegraph",
        "category": "media",
        "url": "https://telegra.ph/@{username}",
        "presence_strs": ["Telegraph", "profile", "page"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["publishing", "article", "minimal"],
    },
    {
        "name": "wikipedia",
        "category": "education",
        "url": "https://en.wikipedia.org/wiki/User:{username}",
        "presence_strs": ["Wikipedia", "User:", "contributions"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["encyclopedia", "knowledge", "popular"],
    },
    {
        "name": "wikidata",
        "category": "education",
        "url": "https://www.wikidata.org/wiki/User:{username}",
        "presence_strs": ["Wikidata", "User:", "contributions"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["data", "knowledge", "structured"],
    },
    {
        "name": "mixcloud",
        "category": "media",
        "url": "https://www.mixcloud.com/{username}/",
        "presence_strs": ["Mixcloud", "uploads", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["music", "dj", "radio"],
    },
    {
        "name": "8tracks",
        "category": "media",
        "url": "https://8tracks.com/{username}",
        "presence_strs": ["8tracks", "mixes", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["music", "playlist", "mix"],
    },
    {
        "name": "imgur",
        "category": "media",
        "url": "https://imgur.com/user/{username}",
        "presence_strs": ["Imgur", "profile", "comments"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["image", "sharing", "popular"],
    },
    {
        "name": "500px",
        "category": "media",
        "url": "https://500px.com/p/{username}",
        "presence_strs": ["500px", "profile", "photos"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["photography", "portfolio", "professional"],
    },
    {
        "name": "unsplash",
        "category": "media",
        "url": "https://unsplash.com/@{username}",
        "presence_strs": ["Unsplash", "photos", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["photo", "stock", "free"],
    },
    {
        "name": "vsco",
        "category": "media",
        "url": "https://vsco.co/{username}/gallery",
        "presence_strs": ["VSCO", "gallery", "images"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["photo", "editing", "mobile"],
    },
    {
        "name": "meetup",
        "category": "social",
        "url": "https://www.meetup.com/members/{username}/",
        "presence_strs": ["Meetup", "member", "groups"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["events", "community", "local"],
    },
    {
        "name": "eventbrite",
        "category": "social",
        "url": "https://www.eventbrite.com/o/{username}",
        "presence_strs": ["Eventbrite", "events", "organizer"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["events", "tickets", "organizer"],
    },
    {
        "name": "crunchyroll",
        "category": "media",
        "url": "https://www.crunchyroll.com/user/{username}",
        "presence_strs": ["Crunchyroll", "profile", "anime"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["anime", "streaming", "entertainment"],
    },
    {
        "name": "myanimelist",
        "category": "media",
        "url": "https://myanimelist.net/profile/{username}",
        "presence_strs": ["MyAnimeList", "profile", "anime"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["anime", "manga", "database"],
    },
    {
        "name": "anilist",
        "category": "media",
        "url": "https://anilist.co/user/{username}/",
        "presence_strs": ["AniList", "anime", "manga"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["anime", "manga", "social"],
    },
    {
        "name": "trello",
        "category": "tech",
        "url": "https://trello.com/{username}",
        "presence_strs": ["Trello", "boards", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["productivity", "kanban", "project"],
    },
    {
        "name": "asana",
        "category": "tech",
        "url": "https://app.asana.com/0/{username}/list",
        "presence_strs": ["Asana", "tasks", "workspace"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["productivity", "project", "team"],
    },
    {
        "name": "airtable",
        "category": "tech",
        "url": "https://airtable.com/{username}",
        "presence_strs": ["Airtable", "bases", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["database", "spreadsheet", "collaboration"],
    },
    {
        "name": "carrd",
        "category": "tech",
        "url": "https://{username}.carrd.co",
        "presence_strs": ["carrd", "landing page"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["landing", "website", "simple"],
    },
    {
        "name": "linktree",
        "category": "social",
        "url": "https://linktr.ee/{username}",
        "presence_strs": ["Linktree", "links", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["popular", "bio", "links"],
    },
    {
        "name": "bio_link",
        "category": "social",
        "url": "https://bio.link/{username}",
        "presence_strs": ["bio.link", "links", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["bio", "links"],
    },
    {
        "name": "sketchfab",
        "category": "tech",
        "url": "https://sketchfab.com/{username}",
        "presence_strs": ["Sketchfab", "models", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["3d", "models", "creative"],
    },
    {
        "name": "thingiverse",
        "category": "tech",
        "url": "https://www.thingiverse.com/{username}/designs",
        "presence_strs": ["Thingiverse", "designs", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["3d", "printing", "maker"],
    },
    {
        "name": "hackthebox",
        "category": "education",
        "url": "https://app.hackthebox.com/profile/{username}",
        "presence_strs": ["Hack The Box", "profile", "rank"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["security", "ctf", "hacking"],
    },
    {
        "name": "tryhackme",
        "category": "education",
        "url": "https://tryhackme.com/p/{username}",
        "presence_strs": ["TryHackMe", "profile", "rank"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["security", "learning", "ctf"],
    },
    {
        "name": "bugcrowd",
        "category": "tech",
        "url": "https://bugcrowd.com/{username}",
        "presence_strs": ["Bugcrowd", "profile", "bounties"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["security", "bugbounty", "crowdsourced"],
    },
    {
        "name": "hackerone",
        "category": "tech",
        "url": "https://hackerone.com/{username}",
        "presence_strs": ["HackerOne", "profile", "bounties"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["security", "bugbounty", "popular"],
    },
    {
        "name": "intigriti",
        "category": "tech",
        "url": "https://www.intigriti.com/profile/{username}",
        "presence_strs": ["Intigriti", "profile", "researcher"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["security", "bugbounty", "europe"],
    },
    {
        "name": "virus_total",
        "category": "tech",
        "url": "https://www.virustotal.com/gui/user/{username}",
        "presence_strs": ["VirusTotal", "profile", "contributions"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["security", "malware", "analysis"],
    },
    {
        "name": "shodan",
        "category": "tech",
        "url": "https://www.shodan.io/user/{username}",
        "presence_strs": ["Shodan", "profile", "reports"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["security", "iot", "search"],
    },
    {
        "name": "censys",
        "category": "tech",
        "url": "https://search.censys.io/user/{username}",
        "presence_strs": ["Censys", "profile", "reports"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["security", "iot", "search"],
    },
    {
        "name": "gitee",
        "category": "tech",
        "url": "https://gitee.com/{username}",
        "presence_strs": ["Gitee", "profile", "repositories"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["code", "vcs", "china"],
    },
    {
        "name": "juejin",
        "category": "tech",
        "url": "https://juejin.cn/user/{username}",
        "presence_strs": ["juejin", "profile", "articles"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["tech", "blog", "china"],
    },
    {
        "name": "zhihu",
        "category": "forum",
        "url": "https://www.zhihu.com/people/{username}",
        "presence_strs": ["zhihu", "profile", "answers"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["qa", "knowledge", "china"],
    },
    {
        "name": "bilibili",
        "category": "media",
        "url": "https://space.bilibili.com/{username}",
        "presence_strs": ["bilibili", "video", "follower"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["video", "streaming", "china"],
    },
    {
        "name": "douyin",
        "category": "media",
        "url": "https://www.douyin.com/user/{username}",
        "presence_strs": ["douyin", "video", "follower"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["video", "short", "china"],
    },
    {
        "name": "weibo",
        "category": "social",
        "url": "https://weibo.com/{username}",
        "presence_strs": ["weibo", "profile", "follow"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["social", "microblog", "china"],
    },
    {
        "name": "csdn",
        "category": "tech",
        "url": "https://blog.csdn.net/{username}",
        "presence_strs": ["CSDN", "blog", "articles"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["tech", "blog", "china"],
    },
    {
        "name": "segmentfault",
        "category": "tech",
        "url": "https://segmentfault.com/u/{username}",
        "presence_strs": ["SegmentFault", "profile", "answers"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["tech", "qa", "china"],
    },
    {
        "name": "xiaohongshu",
        "category": "social",
        "url": "https://www.xiaohongshu.com/user/profile/{username}",
        "presence_strs": ["xiaohongshu", "profile", "notes"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["social", "lifestyle", "china"],
    },
    {
        "name": "douban",
        "category": "social",
        "url": "https://www.douban.com/people/{username}/",
        "presence_strs": ["douban", "profile", "review"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["social", "review", "china"],
    },
    {
        "name": "npmjs2",
        "category": "tech",
        "url": "https://www.npmjs.com/~{username}",
        "presence_strs": ["npm", "packages"],
        "absence_strs": ["not found", "404"],
        "method": "html",
        "tags": ["javascript", "registry"],
    },
    {
        "name": "rubygems",
        "category": "tech",
        "url": "https://rubygems.org/profiles/{username}",
        "presence_strs": ["RubyGems", "gems", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["ruby", "registry"],
    },
    {
        "name": "cratesio",
        "category": "tech",
        "url": "https://crates.io/users/{username}",
        "presence_strs": ["crates.io", "crates", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["rust", "registry"],
    },
    {
        "name": "packagist",
        "category": "tech",
        "url": "https://packagist.org/users/{username}/",
        "presence_strs": ["Packagist", "packages", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["php", "registry"],
    },
    {
        "name": "nuget",
        "category": "tech",
        "url": "https://www.nuget.org/profiles/{username}",
        "presence_strs": ["NuGet", "packages", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["dotnet", "registry"],
    },
    {
        "name": "maven",
        "category": "tech",
        "url": "https://search.maven.org/~{username}",
        "presence_strs": ["Maven", "artifacts", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["java", "registry"],
    },
    {
        "name": "homebrew",
        "category": "tech",
        "url": "https://github.com/homebrew",
        "check_url": "https://formulae.brew.sh/api/formula/{username}.json",
        "presence_strs": ["\"name\":\"{}\"", "\"version\""],
        "absence_strs": ["404", "not found"],
        "method": "json",
        "tags": ["macos", "package", "cli"],
    },
    {
        "name": "aur",
        "category": "tech",
        "url": "https://aur.archlinux.org/packages?K={username}",
        "presence_strs": ["AUR", "packages", "results"],
        "absence_strs": ["0 packages found", "no results"],
        "method": "html",
        "tags": ["linux", "arch", "package"],
    },
    {
        "name": "flathub",
        "category": "tech",
        "url": "https://flathub.org/apps/search?q={username}",
        "presence_strs": ["Flathub", "apps", "results"],
        "absence_strs": ["no results", "0 apps"],
        "method": "html",
        "tags": ["linux", "flatpak", "package"],
    },
    {
        "name": "cargo_search",
        "category": "tech",
        "url": "https://crates.io/api/v1/crates?q={username}",
        "presence_strs": ["\"crates\"", "\"name\""],
        "absence_strs": ["\"crates\":[]"],
        "method": "json",
        "tags": ["rust", "search"],
    },
    {
        "name": "powershellgallery",
        "category": "tech",
        "url": "https://www.powershellgallery.com/profiles/{username}",
        "presence_strs": ["PowerShell Gallery", "packages", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["powershell", "registry"],
    },
    {
        "name": "chrome_webstore",
        "category": "tech",
        "url": "https://chromewebstore.google.com/search/{username}",
        "presence_strs": ["Chrome Web Store", "extensions", "results"],
        "absence_strs": ["no results", "0 results"],
        "method": "html",
        "tags": ["chrome", "extension", "browser"],
    },
    {
        "name": "firefox_addons",
        "category": "tech",
        "url": "https://addons.mozilla.org/en-US/firefox/search?q={username}",
        "presence_strs": ["Add-ons", "extensions", "results"],
        "absence_strs": ["no results", "0 results"],
        "method": "html",
        "tags": ["firefox", "extension", "browser"],
    },
    {
        "name": "safari_extensions",
        "category": "tech",
        "url": "https://apps.apple.com/search/{username}%20extension",
        "presence_strs": ["App Store", "results", "extension"],
        "absence_strs": ["no results", "0 results"],
        "method": "html",
        "tags": ["safari", "extension", "apple"],
    },
    {
        "name": "vscode_marketplace",
        "category": "tech",
        "url": "https://marketplace.visualstudio.com/search?term={username}",
        "presence_strs": ["Visual Studio Code Marketplace", "extensions", "results"],
        "absence_strs": ["no results", "0 results"],
        "method": "html",
        "tags": ["vscode", "extension", "ide"],
    },
    {
        "name": "jetbrains_plugins",
        "category": "tech",
        "url": "https://plugins.jetbrains.com/search?search={username}",
        "presence_strs": ["JetBrains", "plugins", "results"],
        "absence_strs": ["no results", "0 results"],
        "method": "html",
        "tags": ["jetbrains", "ide", "plugin"],
    },
    {
        "name": "obsidian_plugins",
        "category": "tech",
        "url": "https://obsidian.md/plugins?id={username}",
        "presence_strs": ["Obsidian", "plugin", "description"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["obsidian", "plugin", "notes"],
    },
    {
        "name": "sublime_packages",
        "category": "tech",
        "url": "https://packagecontrol.io/search/{username}",
        "presence_strs": ["Package Control", "packages", "results"],
        "absence_strs": ["no results", "0 results"],
        "method": "html",
        "tags": ["sublime", "editor", "package"],
    },
    {
        "name": "vim_plugins",
        "category": "tech",
        "url": "https://vimawesome.com/?q={username}",
        "presence_strs": ["Vim Awesome", "plugins", "results"],
        "absence_strs": ["no results", "0 results"],
        "method": "html",
        "tags": ["vim", "editor", "plugin"],
    },
    {
        "name": "telegram",
        "category": "social",
        "url": "https://t.me/{username}",
        "presence_strs": ["Telegram", "member", "messages"],
        "absence_strs": ["not found", "404", "If you have Telegram"],
        "method": "html",
        "tags": ["popular", "messaging", "encrypted"],
    },
    {
        "name": "signal",
        "category": "social",
        "url": "https://signal.me/#p/{username}",
        "presence_strs": ["Signal", "profile"],
        "absence_strs": ["not found", "404"],
        "method": "html",
        "tags": ["messaging", "encrypted", "privacy"],
    },
    {
        "name": "whatsapp",
        "category": "social",
        "url": "https://wa.me/{username}",
        "presence_strs": ["WhatsApp", "chat"],
        "absence_strs": ["not found", "404"],
        "method": "html",
        "tags": ["popular", "messaging", "encrypted"],
    },
    {
        "name": "line",
        "category": "social",
        "url": "https://line.me/ti/p/{username}",
        "presence_strs": ["LINE", "profile"],
        "absence_strs": ["not found", "404", "Invalid"],
        "method": "html",
        "tags": ["messaging", "asia"],
    },
    {
        "name": "kakaotalk",
        "category": "social",
        "url": "https://pf.kakao.com/{username}",
        "presence_strs": ["Kakao", "profile", "channel"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["messaging", "korea"],
    },
    {
        "name": "discord_server",
        "category": "gaming",
        "url": "https://discord.gg/{username}",
        "presence_strs": ["Discord", "server", "members"],
        "absence_strs": ["not found", "404", "Invite Invalid"],
        "method": "html",
        "tags": ["gaming", "community", "chat"],
    },
    {
        "name": "slack",
        "category": "tech",
        "url": "https://{username}.slack.com",
        "presence_strs": ["Slack", "sign in", "workspace"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["team", "communication", "workspace"],
    },
    {
        "name": "matrix",
        "category": "tech",
        "url": "https://matrix.to/#/@{username}:matrix.org",
        "presence_strs": ["Matrix", "Element", "chat"],
        "absence_strs": ["not found", "404"],
        "method": "html",
        "tags": ["messaging", "decentralized", "open"],
    },
    {
        "name": "rocket_chat",
        "category": "tech",
        "url": "https://open.rocket.chat/direct/{username}",
        "presence_strs": ["Rocket.Chat", "chat"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["messaging", "open", "team"],
    },
    {
        "name": "mattermost",
        "category": "tech",
        "url": "https://mattermost.com/{username}",
        "presence_strs": ["Mattermost", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["messaging", "open", "team"],
    },
    {
        "name": "zulip",
        "category": "tech",
        "url": "https://{username}.zulipchat.com",
        "presence_strs": ["Zulip", "chat", "organization"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["messaging", "open", "team"],
    },
    {
        "name": "gitter",
        "category": "tech",
        "url": "https://gitter.im/{username}",
        "presence_strs": ["Gitter", "chat", "room"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["messaging", "dev", "community"],
    },
    {
        "name": "revolt",
        "category": "gaming",
        "url": "https://revolt.chat/{username}",
        "presence_strs": ["Revolt", "chat", "server"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["messaging", "gaming", "open"],
    },
    {
        "name": "guilded",
        "category": "gaming",
        "url": "https://www.guilded.gg/{username}",
        "presence_strs": ["Guilded", "profile", "servers"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "community", "team"],
    },
    {
        "name": "steam_community",
        "category": "gaming",
        "url": "https://steamcommunity.com/groups/{username}",
        "presence_strs": ["Steam Community", "group", "members"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "community", "pc"],
    },
    {
        "name": "epicgames",
        "category": "gaming",
        "url": "https://store.epicgames.com/en-US/p/{username}",
        "presence_strs": ["Epic Games", "game", "store"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "store", "pc"],
    },
    {
        "name": "playstation",
        "category": "gaming",
        "url": "https://psnprofiles.com/{username}",
        "presence_strs": ["PSNProfiles", "profile", "trophies"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "console", "sony"],
    },
    {
        "name": "xbox",
        "category": "gaming",
        "url": "https://xgamergen.com/{username}",
        "presence_strs": ["Xbox", "gamerscore", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "console", "microsoft"],
    },
    {
        "name": "origin",
        "category": "gaming",
        "url": "https://www.ea.com/games/{username}",
        "presence_strs": ["EA", "games", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "pc", "ea"],
    },
    {
        "name": "ubisoft",
        "category": "gaming",
        "url": "https://ubisoftconnect.com/en-US/profile/{username}",
        "presence_strs": ["Ubisoft", "profile", "games"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "pc", "ubisoft"],
    },
    {
        "name": "gog",
        "category": "gaming",
        "url": "https://www.gog.com/en/u/{username}",
        "presence_strs": ["GOG", "games", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "pc", "drm-free"],
    },
    {
        "name": "moba_games",
        "category": "gaming",
        "url": "https://www.mobafire.com/member/{username}",
        "presence_strs": ["MOBAFire", "member", "builds"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "moba", "guides"],
    },
    {
        "name": "op.gg",
        "category": "gaming",
        "url": "https://www.op.gg/summoners/{username}",
        "presence_strs": ["OP.GG", "summoner", "rank"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "moba", "stats"],
    },
    {
        "name": "tracker_gg",
        "category": "gaming",
        "url": "https://tracker.gg/{username}",
        "presence_strs": ["Tracker", "profile", "stats"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "stats", "multi-game"],
    },
    {
        "name": "speedrun",
        "category": "gaming",
        "url": "https://www.speedrun.com/user/{username}",
        "presence_strs": ["Speedrun.com", "profile", "runs"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "speedrun", "records"],
    },
    {
        "name": "moddb",
        "category": "gaming",
        "url": "https://www.moddb.com/members/{username}",
        "presence_strs": ["Mod DB", "member", "mods"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "mods", "community"],
    },
    {
        "name": "nexusmods",
        "category": "gaming",
        "url": "https://nexusmods.com/users/{username}",
        "presence_strs": ["Nexus Mods", "profile", "mods"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "mods", "popular"],
    },
    {
        "name": "curseforge",
        "category": "gaming",
        "url": "https://www.curseforge.com/members/{username}",
        "presence_strs": ["CurseForge", "member", "projects"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "mods", "minecraft"],
    },
    {
        "name": "namemc",
        "category": "gaming",
        "url": "https://namemc.com/profile/{username}",
        "presence_strs": ["NameMC", "profile", "skins"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["minecraft", "skin", "cape"],
    },
    {
        "name": "planet_minecraft",
        "category": "gaming",
        "url": "https://www.planetminecraft.com/member/{username}/",
        "presence_strs": ["Planet Minecraft", "member", "submissions"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["minecraft", "community"],
    },
    {
        "name": "skindex",
        "category": "gaming",
        "url": "https://www.minecraftskins.com/search/?search={username}",
        "presence_strs": ["Minecraft Skins", "results"],
        "absence_strs": ["no results", "0 skins"],
        "method": "html",
        "tags": ["minecraft", "skins"],
    },
    {
        "name": "faceit",
        "category": "gaming",
        "url": "https://www.faceit.com/en/players/{username}",
        "presence_strs": ["FACEIT", "profile", "elo"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "competitive", "cs2"],
    },
    {
        "name": "esea",
        "category": "gaming",
        "url": "https://play.esea.net/users/{username}",
        "presence_strs": ["ESEA", "profile", "rank"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "competitive", "cs"],
    },
    {
        "name": "celtics",
        "category": "gaming",
        "url": "https://www.halowaypoint.com/en-us/players/{username}",
        "presence_strs": ["Halo", "Waypoint", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "halo", "console"],
    },
    {
        "name": "fortnite_tracker",
        "category": "gaming",
        "url": "https://fortnitetracker.com/profile/all/{username}",
        "presence_strs": ["Fortnite Tracker", "profile", "stats"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "fortnite", "stats"],
    },
    {
        "name": "apex_tracker",
        "category": "gaming",
        "url": "https://apex.tracker.gg/apex/profile/origin/{username}/overview",
        "presence_strs": ["Apex Legends", "profile", "stats"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "apex", "stats"],
    },
    {
        "name": "valorant_tracker",
        "category": "gaming",
        "url": "https://tracker.gg/valorant/profile/riot/{username}/overview",
        "presence_strs": ["Valorant", "profile", "stats"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "valorant", "stats"],
    },
    {
        "name": "overwatch_tracker",
        "category": "gaming",
        "url": "https://overwatch.tracker.gg/profile/pc/{username}/overview",
        "presence_strs": ["Overwatch", "profile", "stats"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "overwatch", "stats"],
    },
    {
        "name": "smashgg",
        "category": "gaming",
        "url": "https://www.start.gg/user/{username}",
        "presence_strs": ["start.gg", "profile", "tournaments"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "esports", "tournament"],
    },
    {
        "name": "challonge",
        "category": "gaming",
        "url": "https://challonge.com/users/{username}",
        "presence_strs": ["Challonge", "tournaments", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "tournament", "bracket"],
    },
    {
        "name": "osu",
        "category": "gaming",
        "url": "https://osu.ppy.sh/users/{username}",
        "presence_strs": ["osu!", "profile", "pp"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "rhythm", "music"],
    },
    {
        "name": "newgrounds",
        "category": "gaming",
        "url": "https://{username}.newgrounds.com",
        "presence_strs": ["Newgrounds", "profile", "content"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "creative", "community"],
    },
    {
        "name": "kongregate",
        "category": "gaming",
        "url": "https://www.kongregate.com/accounts/{username}",
        "presence_strs": ["Kongregate", "profile", "level"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "flash", "browser"],
    },
    {
        "name": "miniclip",
        "category": "gaming",
        "url": "https://www.miniclip.com/user/{username}",
        "presence_strs": ["Miniclip", "profile", "games"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "casual", "browser"],
    },
    {
        "name": "poki",
        "category": "gaming",
        "url": "https://poki.com/en/search?q={username}",
        "presence_strs": ["Poki", "games", "results"],
        "absence_strs": ["no results", "0 games"],
        "method": "html",
        "tags": ["gaming", "casual", "browser"],
    },
    {
        "name": "armorgames",
        "category": "gaming",
        "url": "https://armorgames.com/user/{username}",
        "presence_strs": ["Armor Games", "profile", "games"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "flash", "browser"],
    },
    {
        "name": "y8",
        "category": "gaming",
        "url": "https://www.y8.com/profile/{username}",
        "presence_strs": ["Y8", "profile", "games"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "casual", "browser"],
    },
    {
        "name": "coolmath",
        "category": "gaming",
        "url": "https://www.coolmathgames.com/user/{username}",
        "presence_strs": ["Coolmath", "profile", "games"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "educational", "browser"],
    },
    {
        "name": "roblox_developer",
        "category": "tech",
        "url": "https://create.roblox.com/users/{username}",
        "presence_strs": ["Roblox", "creator", "creations"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "development", "creator"],
    },
    {
        "name": "unity_connect",
        "category": "tech",
        "url": "https://connect.unity.com/u/{username}",
        "presence_strs": ["Unity", "Connect", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gamedev", "engine", "community"],
    },
    {
        "name": "unreal_engine",
        "category": "tech",
        "url": "https://forums.unrealengine.com/u/{username}",
        "presence_strs": ["Unreal Engine", "profile", "posts"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gamedev", "engine", "community"],
    },
    {
        "name": "godot",
        "category": "tech",
        "url": "https://godot.community/u/{username}",
        "presence_strs": ["Godot", "profile", "posts"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gamedev", "engine", "open"],
    },
    {
        "name": "itch_devlog",
        "category": "gaming",
        "url": "https://itch.io/profile/{username}",
        "presence_strs": ["itch.io", "profile", "devlogs"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gamedev", "indie", "devlog"],
    },
    {
        "name": "gamejolt",
        "category": "gaming",
        "url": "https://gamejolt.com/@{username}",
        "presence_strs": ["Game Jolt", "profile", "games"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gamedev", "indie", "community"],
    },
    {
        "name": "indiedb",
        "category": "gaming",
        "url": "https://www.indiedb.com/members/{username}",
        "presence_strs": ["Indie DB", "member", "projects"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gamedev", "indie", "community"],
    },
    {
        "name": "steam_workshop",
        "category": "gaming",
        "url": "https://steamcommunity.com/id/{username}/myworkshopfiles/",
        "presence_strs": ["Steam Community", "Workshop", "items"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["gaming", "workshop", "mods"],
    },
    {
        "name": "twitch_clips",
        "category": "media",
        "url": "https://www.twitch.tv/{username}/clip",
        "presence_strs": ["Twitch", "clips", "channel"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["streaming", "clips", "gaming"],
    },
    {
        "name": "kick",
        "category": "media",
        "url": "https://kick.com/{username}",
        "presence_strs": ["Kick", "profile", "streams"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["streaming", "gaming", "popular"],
    },
    {
        "name": "rumble",
        "category": "media",
        "url": "https://rumble.com/c/{username}",
        "presence_strs": ["Rumble", "videos", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["video", "streaming", "alternative"],
    },
    {
        "name": "peertube",
        "category": "media",
        "url": "https://framatube.org/accounts/{username}",
        "presence_strs": ["PeerTube", "profile", "videos"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["video", "federated", "open"],
    },
    {
        "name": "lbry",
        "category": "media",
        "url": "https://odysee.com/@{username}",
        "presence_strs": ["Odysee", "content", "followers"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["video", "blockchain", "decentralized"],
    },
    {
        "name": "dailymotion",
        "category": "media",
        "url": "https://www.dailymotion.com/{username}",
        "presence_strs": ["Dailymotion", "videos", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["video", "streaming", "european"],
    },
    {
        "name": "nicovideo",
        "category": "media",
        "url": "https://www.nicovideo.jp/user/{username}",
        "presence_strs": ["niconico", "videos", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["video", "japan", "streaming"],
    },
    {
        "name": "bilibili_intl",
        "category": "media",
        "url": "https://www.bilibili.tv/en/accounts/{username}",
        "presence_strs": ["bilibili", "videos", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["video", "international", "china"],
    },
    {
        "name": "twitch_vod",
        "category": "media",
        "url": "https://www.twitch.tv/{username}/videos",
        "presence_strs": ["Twitch", "videos", "VOD"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["streaming", "vods", "gaming"],
    },
    {
        "name": "youtube_channels",
        "category": "media",
        "url": "https://www.youtube.com/c/{username}",
        "presence_strs": ["YouTube", "channel", "videos"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["video", "popular", "channels"],
    },
    {
        "name": "periscope",
        "category": "media",
        "url": "https://www.pscp.tv/{username}",
        "presence_strs": ["Periscope", "profile", "broadcasts"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["live", "streaming", "twitter"],
    },
    {
        "name": "clubhouse",
        "category": "social",
        "url": "https://www.clubhouse.com/@{username}",
        "presence_strs": ["Clubhouse", "profile", "followers"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["social", "audio", "voice"],
    },
    {
        "name": "spaces",
        "category": "social",
        "url": "https://huggingface.co/spaces/{username}",
        "presence_strs": ["Hugging Face", "Spaces", "models"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["ai", "ml", "models"],
    },
    {
        "name": "huggingface",
        "category": "tech",
        "url": "https://huggingface.co/{username}",
        "presence_strs": ["Hugging Face", "profile", "models"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["ai", "ml", "popular"],
    },
    {
        "name": "replicate",
        "category": "tech",
        "url": "https://replicate.com/{username}",
        "presence_strs": ["Replicate", "models", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["ai", "ml", "deployment"],
    },
    {
        "name": "runwayml",
        "category": "tech",
        "url": "https://runwayml.com/@{username}",
        "presence_strs": ["Runway", "profile", "projects"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["ai", "creative", "video"],
    },
    {
        "name": "midjourney",
        "category": "tech",
        "url": "https://www.midjourney.com/{username}",
        "presence_strs": ["Midjourney", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["ai", "art", "image"],
    },
    {
        "name": "civitai",
        "category": "tech",
        "url": "https://civitai.com/user/{username}",
        "presence_strs": ["Civitai", "profile", "models"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["ai", "art", "image"],
    },
    {
        "name": "kaggle_datasets",
        "category": "education",
        "url": "https://www.kaggle.com/datasets/{username}",
        "presence_strs": ["Kaggle", "datasets", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["data", "ml", "datasets"],
    },
    {
        "name": "colab",
        "category": "education",
        "url": "https://colab.research.google.com/drive",
        "check_url": "https://colab.research.google.com/search?q=author:{username}",
        "presence_strs": ["Colab", "notebooks", "results"],
        "absence_strs": ["no results", "0 notebooks"],
        "method": "html",
        "tags": ["jupyter", "notebook", "google"],
    },
    {
        "name": "deeplearning_ai",
        "category": "education",
        "url": "https://www.deeplearning.ai/{username}",
        "presence_strs": ["DeepLearning.AI", "profile", "courses"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["ai", "ml", "courses"],
    },
    {
        "name": "coursera",
        "category": "education",
        "url": "https://www.coursera.org/user/{username}",
        "presence_strs": ["Coursera", "profile", "courses"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["mooc", "courses", "popular"],
    },
    {
        "name": "udemy",
        "category": "education",
        "url": "https://www.udemy.com/user/{username}/",
        "presence_strs": ["Udemy", "profile", "courses"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["mooc", "courses", "popular"],
    },
    {
        "name": "edx",
        "category": "education",
        "url": "https://courses.edx.org/u/{username}",
        "presence_strs": ["edX", "profile", "courses"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["mooc", "courses", "university"],
    },
    {
        "name": "skillshare",
        "category": "education",
        "url": "https://www.skillshare.com/profile/{username}",
        "presence_strs": ["Skillshare", "profile", "classes"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["learning", "creative", "classes"],
    },
    {
        "name": "duolingo",
        "category": "education",
        "url": "https://www.duolingo.com/profile/{username}",
        "presence_strs": ["Duolingo", "profile", "streak"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["language", "learning", "popular"],
    },
    {
        "name": "codecademy",
        "category": "education",
        "url": "https://www.codecademy.com/profiles/{username}",
        "presence_strs": ["Codecademy", "profile", "courses"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["coding", "learning", "interactive"],
    },
    {
        "name": "free_code_camp",
        "category": "education",
        "url": "https://www.freecodecamp.org/{username}",
        "presence_strs": ["freeCodeCamp", "profile", "certifications"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["coding", "learning", "free"],
    },
    {
        "name": "w3schools",
        "category": "education",
        "url": "https://profile.w3schools.com/{username}",
        "presence_strs": ["w3schools", "profile", "exercises"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["web", "learning", "tutorials"],
    },
    {
        "name": "brave_publishers",
        "category": "tech",
        "url": "https://search.brave.com/search?q=site:publisher.basicattentiontoken.org+{username}",
        "presence_strs": ["publisher", "results"],
        "absence_strs": ["no results", "0 results"],
        "method": "html",
        "tags": ["crypto", "publishing", "brave"],
    },
    {
        "name": "github_gist",
        "category": "tech",
        "url": "https://gist.github.com/{username}",
        "presence_strs": ["gist", "profile", "gists"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["code", "snippets", "github"],
    },
    {
        "name": "github_io",
        "category": "tech",
        "url": "https://{username}.github.io",
        "presence_strs": ["<html", "<head", "<body"],
        "absence_strs": ["404", "not found", "Page not found"],
        "method": "html",
        "tags": ["website", "hosting", "github"],
    },
    {
        "name": "gitpages",
        "category": "tech",
        "url": "https://{username}.gitlab.io",
        "presence_strs": ["<html", "<head", "<body"],
        "absence_strs": ["404", "not found", "Page not found"],
        "method": "html",
        "tags": ["website", "hosting", "gitlab"],
    },
    {
        "name": "readthedocs",
        "category": "tech",
        "url": "https://{username}.readthedocs.io",
        "presence_strs": ["Read the Docs", "docs"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["documentation", "hosting"],
    },
    {
        "name": "docs_rs",
        "category": "tech",
        "url": "https://docs.rs/{username}",
        "presence_strs": ["docs.rs", "documentation"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["rust", "documentation"],
    },
    {
        "name": "pkg_go_dev",
        "category": "tech",
        "url": "https://pkg.go.dev/search?q={username}&m=package",
        "presence_strs": ["pkg.go.dev", "packages", "results"],
        "absence_strs": ["no results", "0 packages"],
        "method": "html",
        "tags": ["go", "documentation", "registry"],
    },
    {
        "name": "jsdelivr",
        "category": "tech",
        "url": "https://www.jsdelivr.com/search?q={username}",
        "presence_strs": ["jsDelivr", "packages", "results"],
        "absence_strs": ["no results", "0 packages"],
        "method": "html",
        "tags": ["cdn", "npm", "packages"],
    },
    {
        "name": "unpkg",
        "category": "tech",
        "url": "https://unpkg.com/browse/{username}/",
        "presence_strs": ["unpkg", "files", "package"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["cdn", "npm", "packages"],
    },
    {
        "name": "cdnjs",
        "category": "tech",
        "url": "https://cdnjs.com/libraries/{username}",
        "presence_strs": ["cdnjs", "library", "files"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["cdn", "js", "libraries"],
    },
    {
        "name": "jenkins",
        "category": "tech",
        "url": "https://plugins.jenkins.io/{username}",
        "presence_strs": ["Jenkins", "plugin", "description"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["ci", "cd", "devops"],
    },
    {
        "name": "docker_hub_search",
        "category": "tech",
        "url": "https://hub.docker.com/search?q={username}",
        "presence_strs": ["Docker Hub", "results", "repositories"],
        "absence_strs": ["no results", "0 results"],
        "method": "html",
        "tags": ["docker", "container", "search"],
    },
    {
        "name": "ghcr",
        "category": "tech",
        "url": "https://github.com/users/{username}/packages/container",
        "presence_strs": ["GitHub", "packages", "container"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["container", "registry", "github"],
    },
    {
        "name": "quay",
        "category": "tech",
        "url": "https://quay.io/repository/{username}",
        "presence_strs": ["Quay", "repository", "tags"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["container", "registry", "redhat"],
    },
    {
        "name": "cloudsmith",
        "category": "tech",
        "url": "https://cloudsmith.io/~{username}",
        "presence_strs": ["Cloudsmith", "profile", "repositories"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["package", "registry", "cloud"],
    },
    {
        "name": "launchpad",
        "category": "tech",
        "url": "https://launchpad.net/~{username}",
        "presence_strs": ["Launchpad", "profile", "projects"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["code", "vcs", "ubuntu"],
    },
    {
        "name": "sourceforge",
        "category": "tech",
        "url": "https://sourceforge.net/u/{username}/profile",
        "presence_strs": ["SourceForge", "profile", "projects"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["code", "hosting", "open"],
    },
    {
        "name": "savannah",
        "category": "tech",
        "url": "https://savannah.gnu.org/users/{username}",
        "presence_strs": ["Savannah", "user", "projects"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["code", "gnu", "free"],
    },
    {
        "name": "freecodecamp_news",
        "category": "media",
        "url": "https://www.freecodecamp.org/news/author/{username}/",
        "presence_strs": ["freeCodeCamp", "News", "author"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["news", "programming", "writing"],
    },
    {
        "name": "dev_to_news",
        "category": "media",
        "url": "https://dev.to/{username}",
        "presence_strs": ["DEV Community", "profile", "posts"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["blog", "programming", "community"],
    },
    {
        "name": "infoq",
        "category": "tech",
        "url": "https://www.infoq.com/{username}/",
        "presence_strs": ["InfoQ", "profile", "articles"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["tech", "news", "enterprise"],
    },
    {
        "name": "dzone",
        "category": "tech",
        "url": "https://dzone.com/users/{username}",
        "presence_strs": ["DZone", "profile", "articles"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["tech", "articles", "enterprise"],
    },
    {
        "name": "smashing",
        "category": "tech",
        "url": "https://www.smashingmagazine.com/author/{username}/",
        "presence_strs": ["Smashing Magazine", "author", "articles"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["design", "webdev", "articles"],
    },
    {
        "name": "css_tricks",
        "category": "tech",
        "url": "https://css-tricks.com/author/{username}/",
        "presence_strs": ["CSS-Tricks", "author", "articles"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["css", "webdev", "articles"],
    },
    {
        "name": "web.dev",
        "category": "tech",
        "url": "https://web.dev/authors/{username}/",
        "presence_strs": ["web.dev", "author", "articles"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["webdev", "performance", "google"],
    },
    {
        "name": "mozilla_hacks",
        "category": "tech",
        "url": "https://hacks.mozilla.org/author/{username}/",
        "presence_strs": ["Mozilla Hacks", "author", "posts"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["mozilla", "webdev", "articles"],
    },
    {
        "name": "netlify_blog",
        "category": "tech",
        "url": "https://www.netlify.com/blog/author/{username}/",
        "presence_strs": ["Netlify", "blog", "author"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["deployment", "blog", "jamstack"],
    },
    {
        "name": "vercel_blog",
        "category": "tech",
        "url": "https://vercel.com/blog/author/{username}",
        "presence_strs": ["Vercel", "blog", "author"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["deployment", "blog", "frontend"],
    },
    {
        "name": "supabase",
        "category": "tech",
        "url": "https://supabase.com/dashboard/project/{username}",
        "presence_strs": ["Supabase", "dashboard", "project"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["database", "backend", "open"],
    },
    {
        "name": "firebase",
        "category": "tech",
        "url": "https://{username}.firebaseapp.com",
        "presence_strs": ["<html", "<head", "Firebase"],
        "absence_strs": ["not found", "404", "Page not found"],
        "method": "html",
        "tags": ["hosting", "backend", "google"],
    },
    {
        "name": "heroku",
        "category": "tech",
        "url": "https://{username}.herokuapp.com",
        "presence_strs": ["<html", "<head", "Application"],
        "absence_strs": ["not found", "404", "No app"],
        "method": "html",
        "tags": ["hosting", "paas", "deployment"],
    },
    {
        "name": "render",
        "category": "tech",
        "url": "https://{username}.onrender.com",
        "presence_strs": ["<html", "<head"],
        "absence_strs": ["not found", "404", "Page not found"],
        "method": "html",
        "tags": ["hosting", "deployment", "cloud"],
    },
    {
        "name": "railway",
        "category": "tech",
        "url": "https://{username}.up.railway.app",
        "presence_strs": ["<html", "<head"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["hosting", "deployment", "cloud"],
    },
    {
        "name": "fly_io",
        "category": "tech",
        "url": "https://{username}.fly.dev",
        "presence_strs": ["<html", "<head"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["hosting", "deployment", "cloud"],
    },
    {
        "name": "deno_deploy",
        "category": "tech",
        "url": "https://{username}.deno.dev",
        "presence_strs": ["<html", "<head", "Deno"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["hosting", "deno", "deployment"],
    },
    {
        "name": "workers_dev",
        "category": "tech",
        "url": "https://{username}.workers.dev",
        "presence_strs": ["<html", "<head", "Cloudflare"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["hosting", "cloudflare", "edge"],
    },
    {
        "name": "cloudflare_pages",
        "category": "tech",
        "url": "https://{username}.pages.dev",
        "presence_strs": ["<html", "<head"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["hosting", "cloudflare", "pages"],
    },
    {
        "name": "netlify_site",
        "category": "tech",
        "url": "https://{username}.netlify.app",
        "presence_strs": ["<html", "<head"],
        "absence_strs": ["not found", "404", "Page not found"],
        "method": "html",
        "tags": ["hosting", "netlify", "jamstack"],
    },
    {
        "name": "surge_sh",
        "category": "tech",
        "url": "https://{username}.surge.sh",
        "presence_strs": ["<html", "<head"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["hosting", "static", "cli"],
    },
    {
        "name": "tiiny_host",
        "category": "tech",
        "url": "https://{username}.tiiny.site",
        "presence_strs": ["<html", "<head"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["hosting", "landing", "simple"],
    },
    {
        "name": "neocities",
        "category": "tech",
        "url": "https://{username}.neocities.org",
        "presence_strs": ["Neocities", "site", "profile"],
        "absence_strs": ["not found", "404", "page not found"],
        "method": "html",
        "tags": ["hosting", "static", "retro"],
    },
    {
        "name": "github_pages_custom",
        "category": "tech",
        "url": "https://{username}.github.io",
        "check_url": "https://api.github.com/repos/{username}/{username}.github.io",
        "presence_strs": ["\"id\"", "\"html_url\"", "\"description\""],
        "absence_strs": ["Not Found", "404"],
        "method": "json",
        "tags": ["website", "github", "pages"],
    },
]


def get_all_sites():
    """Return all sites in the database."""
    return list(SITES)


def get_sites_by_category(category):
    """Return sites filtered by category."""
    return [s for s in SITES if s.get("category") == category]


def get_sites_by_categories(categories):
    """Return sites filtered by multiple categories."""
    return [s for s in SITES if s.get("category") in categories]


def get_sites_excluding_categories(exclude_categories):
    """Return sites excluding specified categories."""
    return [s for s in SITES if s.get("category") not in exclude_categories]


def get_site_count():
    """Return total number of sites."""
    return len(SITES)


def get_categories():
    """Return all available categories."""
    return dict(CATEGORIES)
